const http = require("http");
const WebSocket = require("ws");
let views = require("./views.js");
let mess = require("./messages.js");
/*let db = new WebSocket("http://de1.bot-hosting.net:20558");
db.on("open", () => {
  console.log("NICE IT WORKED ESCLIPPY!");
});*/
let view;
let start = new Date();
view = views.views;
const fs = require("fs");
/*process.on("uncaughtException", () => {
  console.log("error!");
});*/
// --- HTTP Server ---
const server = http.createServer((req, res) => {
  let sn = new Date();
  let a = sn.getDate();
  let b = sn.getMonth();
  res.writeHead(200, { "Content-Type": "text/html" });
  console.log(req.url);
  if (req.url === "/faq" || req.url === "/qna") {
    res.end(`<!DOCTYPE html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0">
  <style>
  body {
  font-family: sans-serif;
  user-select: none;
  }
  a {
  color: black;
  }
  </style>
  </head>
  <body>
  <font size="7">Questions and Answers</font>
  <br><br>
  <hr>
  <details>
  <summary><font size="5"><b>Where do messages go when sent?</b></font></summary>
  <sub><font size="5">Messages are sent through <font color="black"><a href="https://en.wikipedia.org/wiki/WebSocket">WebSocket</a></font> traffic, as JSON.<br>The EXACT data sent is as follows:<br>
  <ul>
  <li>The name you send the message through</li>
  <li>The message you provided</li>
  <li>Any embed (true/false)</li>
  </ul>
  But before that, checkings are done, such as:
  <ul>
  <li>Does it start with a '/', and register it as a command?</li>
  <li>If not, is it not a blank message?</li>
  <li>Do you already have a name to be chatting with?</li>
  </ul>
  If the conditions are satisfactory, the message is sent to the server, where it is sent to others.
  </font><hr></sub>
  </details>
  <details>
  <summary><font size="5"><b>What happens to the messages when they reach the server?</b></font></summary>
  <sub><font size="5">Once the message completes it's journey to reach the server, it's checked for the following:
  <ul>
  <li>Are you muted?</li>
  <li>If not, is the message blank?</li>
  <li>Is the last message sent under 200ms? (If yes, that's spam)</li>
  <li>Does the message contain any innapropriate words/slurs?</li>
  <li>Does the message contain any embed? (true/false)</li>
  </ul>
  If the conditions are satisfactory, the message is sent to the other clients.
  </font><hr></sub>
  </details>
  <details>
  <summary><b><font size="5">How does the client interpret the message?</font></b></summary>
  <sub><font size="5">
  Usually, it's JSON. But then, the client breaks it down into 3 parts:
  <ul>
  <li>The username</li>
  <li>The actual message</li>
  <li>The message ID (generated by the server)</li>
  </ul>
  If it has an embed (true/false), it isn't shown right away.
  <br>
  The client holds that message, and when the server sends the embed of the file,
  <br>
  the message appends the embed (video/image/audio/link).
  <br>
  Then, it's put straight into a html code arranging and assembling the parts.
  <br>
  After that, the message is displayed in the chat!
  </font><hr></sub>
  </details>
  <details>
  <summary><font size="5"><b>How are my embeds sent? Is anyone seeing my (video/audio/image/etc.)?</b></font></summary>
  <sub><font size="5">
  Absolutely not! There isn't anyone seeing your embed at all, indeed.
  <br>
  Firstly, the file type is configured. Then, the embed is sent over the server. From there,<br>
  it's broadcasted to all the clients. Afterward, the client loads the file (e.g mp4, jpg, png, mp3, etc.) as a <br>temporary "blob" file.<br>
  The servers i own are usually not that capable to "store" files.<br><br>
  The files sent through the server are directly sent to the client to load. There is <i>NOTHING</i> in between<br>that could actually "store" or "see" the files you send.
  </font><hr></sub>
  </details>
  <details>
  <summary><font size="5"><b>Is there any "admin/mod" or a way to join membership with the dev?</b></font></summary>
  <sub><font size="5">No. There is no "admin/mod" for the chatroom, as i am the dev and "mod/admin".<br>Sorry, but I do not wish to join any membership with anyone else. I am rather comfortable coding<br> and developing this chatroom alone. But thanks for being generous enough to ask, if you did! :D</font><hr></sub>
  </details>
  <details>
  <summary><font size="5"><b>Is the chatroom 'open-source'?</b></font></summary>
  <sub><font size="5">No, this chatroom is not open-source.</font></sub>
  </details>
  <hr>
  <font size="5">Start chatting now! Any questions? If they feel important, they will be added to this list too along with the answers!</font>
  </body>`);
  } else {
    res.end(`<!DOCTYPE html>
  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0, width=device-width">
  <style>
  body {
  font-family: sans-serif;
  overflow-x: 'hidden';
  }${
    b === 11 || b === 0
      ? `
      .santa {
      animation: b 5s infinite;
      }
      @keyframes b {
        0% { color: red; }
        25% { color: orange; }
        50% { color: red; }
        75% { color: orange; }
        100% { color: red; }
      }
      .grinch {
        animation: a 5s infinite;
        cursor: pointer;
        user-select: none;
        }
        @keyframes a {
        0% { color: lightgreen; }
        25% { color: darkgreen; }
        50% { color: lightgreen; }
        75% { color: darkgreen; }
        100% { color: lightgreen; }
        }
  .snowflake {
    position: absolute;
    top: -10px;
    width: 10px;
    height: 10px;
    background-color: black;
    border-radius: 100%;
    opacity: 0.8;
    animation: fall linear infinite;
    }
    @keyframes fall {
    to {
    transform: translateY(100vh) translateX(20vh);
    opacity: 0;
    }
    }
  `
      : ""
  }
  .confetti {
    animation: confett linear;
    background-color: red;
    position: absolute;
    top: -10px;
    left: -10px;
    width: 10px;
    height: 10px;
    transform: rotate(0deg);
    }
    @keyframes confett {
    to {
    transform: translateY(100vh);
    opacity: 0;
    }
    }
    #chat {
    overflow-y: scroll;
    overflow-wrap: break-word;
    }${
      b === 0
        ? `
    .part {
      border-radius: 50%;
      background-color: black;
      width: 10px;
      height: 10px;
      position: fixed;
      }
    @keyframes pa {
      to {
      transform: translateY(30vh);
      opacity: 0;
      }
      }
      @keyframes pb {
      to {
      transform: translateY(-30vh);
      opacity: 0;
      }
      }
      @keyframes pc {
      to {
      transform: translateX(30vh);
      opacity: 0;
      }
      }
      @keyframes pd {
      to {
      transform: translateX(-30vh);
      opacity: 0;
      }
      }
      @keyframes pe {
      to {
      transform: translateX(30vh) translateY(-30vh);
      opacity: 0;
      }
      }
      @keyframes pf {
      to {
      transform: translateX(-30vh) translateY(30vh);
      opacity: 0;
      }
      }
      @keyframes pg {
      to {
      transform: translateX(30vh) translateY(30vh);
      opacity: 0;
      }
      }
      @keyframes ph {
      to {
      transform: translateX(-30vh) translateY(-30vh);
      opacity: 0;
      }
      }`
        : ""
    }
  </style>
  </head>
  <body>
  <span style="position: fixed; font-family: sans-serif; user-select: none; transition: 0.5s; opacity: 1; transform: translate(-50%, -50%) scale(1.5); text-align: center; top: 50%; left: 50%; z-index: 100;" id="intro"><b style="font-size: 30px;">Chat room - ${String(
    Math.floor(view / 2)
  )} Visits</b><br><span id="okay">Connecting...</span> <span id="limit" style="transition: 0.5s;">(?/25)</span><br><input placeholder="Name..." id="name" maxlength="25" disabled><button id="join" disabled>Join</button><button id="spectate">Spectate</button></span>
  <div id="rest" style="transition: 0.5s; opacity: 0;">
  <center><big><big><big><big><b>Chat Room - ${String(
    Math.floor(view / 2)
  )} Visits</b></big></big></big></big></center>
  <div id="chat">
  <font size="6" color="grey">Connecting...</font>
  </div>
  <b id="a" hidden=""><font id="typing"></font><br></b>
  <font color="red" id="o" hidden>Internet connection lost. Please wait while we try to reconnect.<br></font>
  <font color="red" id="o" hidden>The connection was closed. Please wait while we try to reconnect.<br></font>
  <br>
  <span id="chatinput"><input size="30" placeholder="Message" id="message" maxlength="75" disabled><button id="send" disabled>Send</button>
  <br><input id="e" type="file"></span>
  <button id="back" hidden>Back</button>
  </div>
  </body>
  <script>
  let namesubmitted = false;${
    b === 11 || b === 0
      ? `
  let max = ${(a === 25 && b === 11) || b === 0 ? "100" : "50"};
  let snowing = false;
  function confetti() {
    for (let i = 0; i < 50; i++) {
      setTimeout(() => {
      let colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple']
      colors = colors[Math.floor(Math.random()*colors.length)]
      let s = document.createElement('span');
      s.className = 'confetti';
      s.style = "left: "+Math.random()*100+"%; background-color: "+colors+"; animation-duration: "+Number(Number(Math.random() * Math.random())*3+2)+"s;"
      document.body.appendChild(s)
      s.onanimationiteration = () => {
      s.parentNode.removeChild(s)
      }
      }, Math.random() * 5000);
      }
  }
  function onesnow() {
    for (let i = 0; i < max; i++) {
      setTimeout(() => {
      let div = document.createElement('div');
      div.className = "snowflake";
      div.style = "left: "+Math.random()*100+"%; animation-duration: "+Number(Number(Math.random() * Math.random())*5+5)+"s;"
      document.body.appendChild(div)
      console.log(true)
      setTimeout(() => {
      div.onanimationiteration = () => {
        div.parentNode.removeChild(div)
        }
      }, 50);
      }, Math.random() * 5000);
      }
  }
  function snow(what) {
  if (what === true) {
    document.body.style.overflow = 'hidden'
for (let i = 0; i < max && namesubmitted === false && document.getElementsByClassName('snowflake').length < max; i++) {
setTimeout(() => {
if (namesubmitted === false) {
let div = document.createElement('div');
div.className = "snowflake";
div.style = "left: "+Math.random()*100+"%; animation-duration: "+Number(Number(Math.random() * Math.random())*5+5)+"s;"
document.body.appendChild(div)
console.log(true)
}
}, Math.random() * 10000);
}
} else {
  document.body.style.overflow = ''
  for (let i of document.getElementsByClassName('snowflake')) {
    i.onanimationiteration = () => {
    i.parentNode.removeChild(i)
    }
    }
}
}
${b === 11 || b === 0 ? "snow(true)" : ""}
`
      : ""
  }${
      b === 0
        ? `
  window.onmousedown = (e) => {
    let colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple'];
    let col = colors[Math.floor(Math.random() * colors.length)]
    let a = document.createElement('span');
    a.className = "part";
    a.style = "animation: pa linear .5s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let b = document.createElement('span');
    b.className = "part";
    b.style = "animation: pb linear .5s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let c = document.createElement('span');
    c.className = "part";
    c.style = "animation: pc linear .5s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let d = document.createElement('span');
    d.className = "part";
    d.style = "animation: pd linear .5s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let g = document.createElement('span');
    g.className = "part";
    g.style = "animation: pe linear .7s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let h = document.createElement('span');
    h.className = "part";
    h.style = "animation: pf linear .7s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let i = document.createElement('span');
    i.className = "part";
    i.style = "animation: pg linear .7s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    let j = document.createElement('span');
    j.className = "part";
    j.style = "animation: ph linear .7s; top: "+e.clientY+"px; left: "+e.clientX+"px; background-color: "+col+";";
    
    document.body.appendChild(a)
    document.body.appendChild(b)
    document.body.appendChild(c)
    document.body.appendChild(d)
    document.body.appendChild(g)
    document.body.appendChild(h)
    document.body.appendChild(i)
    document.body.appendChild(j)
    
    setTimeout(() => {
    a.parentNode.removeChild(a);
    b.parentNode.removeChild(b);
    c.parentNode.removeChild(c);
    d.parentNode.removeChild(d);
    g.parentNode.removeChild(g);
    h.parentNode.removeChild(h);
    i.parentNode.removeChild(i);
    j.parentNode.removeChild(j);
    }, 500);
    }
  `
        : ""
    }let namee = ""
  let typings = 0;
  let stopAnim = false;
  let focus = false;
  let offline = false;
  let wscrollY
  let editmode = false;
  let editID = "";
  let editOrigin = "";
  let spectate = false;
  window.onoffline = () => {
  offline = true;
  if (namesubmitted === false) {
    document.getElementById('name').disabled = true;
    document.getElementById('join').disabled = true;
    document.getElementById('okay').innerText = 'Internet connection lost.'
    }
  }
  document.getElementById('message').size = window.innerWidth / 10
    document.getElementById('name').size = window.innerWidth / 20
  window.onresize = () => {
    document.getElementById('chat').style.width = window.innerWidth-30+"px"
  document.getElementById('chat').style.height = window.innerHeight-150+"px"
    document.getElementById('message').size = window.innerWidth / 10
    document.getElementById('name').size = window.innerWidth / 20
    }
    document.getElementById('chat').style.width = window.innerWidth-30+"px"
  document.getElementById('chat').style.height = window.innerHeight-150+"px"
  
  window.ononline = () => {
  if (namesubmitted === false) {
      document.getElementById('name').disabled = false;
      document.getElementById('join').disabled = false;
      document.getElementById('okay').innerText = 'Please enter a name.'
      }
  offline = false;
  document.getElementById('o').hidden = true;
  }
  document.getElementById('message').onfocus = () => {
  focus = true;
  }
  document.getElementById('message').onblur = () => {
  focus = false
  }
  document.getElementById('back').onclick = () => {
    spectate = false;
    namesubmitted = false;
    ${b === 11 || b === 0 ? "snow(true)" : ""}
    document.getElementById('join').disabled = false;
    document.getElementById('rest').style.opacity = 0;
        setTimeout(() => {
          document.getElementById('rest').hidden = true;
        document.getElementById('intro').hidden = false;
        setTimeout(() => {
          document.getElementById('chatinput').hidden = false;
          document.getElementById('back').hidden = true;
        document.getElementById('intro').style.opacity = 1;
        }, 10);
        }, 500);
  }
  window.addEventListener('keydown', (e) => {
  if (e.key === 'Escape' && spectate === true) {
  spectate = false;
  document.getElementById('join').disabled = false;
  document.getElementById('chatinput').hidden = false;
  document.getElementById('back').hidden = true;
  document.getElementById('rest').style.opacity = 0;
      setTimeout(() => {
        document.getElementById('rest').hidden = true;
      document.getElementById('intro').hidden = false;
      setTimeout(() => {
      document.getElementById('intro').style.opacity = 1;
      }, 10);
      }, 500);
  } else if (e.key === 'Enter' && document.getElementById('intro').hidden === false) {
  document.getElementById('join').click()
  } else if (e.key === 'Enter' && focus === true) {
  document.getElementById('send').click()
  document.getElementById('message').click();
  }
  })
  console.log('e')
  let ws;
  let reconn = false;
  let muted = false;
  function recon() {
  ws = new WebSocket('https://stunning-adventure-e1ex.onrender.com/');
  ws.onopen = () => {
    //ws.send(JSON.stringify({ type: "ping" })) (This does not do anything to the randomly closing WebSocket problem, where reconnecting is impossible and you have to reload.)
  document.getElementById('name').disabled = false;
  document.getElementById('okay').innerText = 'Please enter a name.';
  document.getElementById('limit').innerText = '('+document.getElementById('name').value.length+'/25)'
  if (document.getElementById('name').value.length > 0) {document.getElementById('join').disabled = false}
  console.log('YEA')
  if (reconn === true) {
    if (document.getElementById('chat').innerHTML.includes('No messages!') && document.getElementById('chat').innerText.length === 91) {} else {
      let sp = document.createElement('span')
    sp.innerHTML += "<hr><center>You were reconnected</center><hr>"
    document.getElementById('chat').appendChild(sp)
    }
    if (document.getElementById('name').value.length > 0 && namesubmitted === true) {
      document.getElementById('name').disabled = true;
      document.getElementById('message').disabled = false;
      document.getElementById('send').disabled = false;
      ws.send(JSON.stringify({type: 'name', data: document.getElementById('name').value}));
      } else {
        if (namesubmitted === false) {
          document.getElementById('name').disabled = false;
          document.getElementById('join').disabled = false;
          document.getElementById('okay').innerText = 'Please enter a name.'
          }
      }
    } else {
      document.getElementById('chat').innerHTML = ${"`"}
      <font size="6" color="grey">No messages!</font><br>
      <font size="4">It looks like there are no messages recieved yet, or there aren't any. Say hi! 
      </div>
      ${"`"}
      console.log('oe')
    }
  }
  let msg = false;
  let thing = '';
  let embed = '';
  ws.onmessage = (msg) => {
  let dat
  try {
  dat = JSON.parse(msg.data)
  } catch (error) {
  console.log(msg)
  console.log(thing);
  console.log(thing.split('/')[1])
  console.log(msg.data)
  let m = new File([msg.data], String(Math.random()).substring(2)+thing.split('/')[1], {
    lastModified: Date.now(),
    type: thing
    })
    console.log('YES')
    let k = URL.createObjectURL(m)
    let img;
  if (thing.includes('video')) {
  img = document.createElement('video');
  img.controls = true;
  img.autoplay = false;
  img.style.width = "300px";
  } else if (thing.includes('audio')) {
    img = document.createElement('audio');
    img.controls = true;
    img.autoplay = false;
    } else if (thing.includes('image')) {
      img = new Image();
  img.style.width = "250px";
    } else {
    img = document.createElement('a');
    img.innerText = String(Math.random()).substring(2)+'.'+thing.split('/')[1];
    img.href = k;
    }
  img.src = k;
  let sp = document.createElement('span')
  let br = document.createElement('br');
  sp.appendChild(br);
  sp.appendChild(img);
  embed.appendChild(sp);
  document.getElementById('chat').appendChild(embed)
  embed = "";
  document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  }
  if (dat.type  !== "addtyping" && dat.type !== "remtyping" && document.getElementById('chat').innerHTML === ${"`"}\n      <font size="6" color="grey">No messages!</font><br>\n      <font size="4">It looks like there are no messages recieved yet, or there aren't any. Say hi! \n      \n      </font>${"`"}) {
  document.getElementById('chat').innerHTML = ''
  }
  /*if (dat.type === "pong") {
    console.log('works')
  setTimeout(() => {
  ws.send(JSON.stringify({ type: "ping" }))
  }, 1000); ( Does not do anything to help in the problem i mentioned above )
  } else */if (dat.type === "thing") {
  thing = dat.data;
  console.log(thing)
  } else if (dat.type === "name") {
  let p = document.createElement('span');
  let a = document.createElement('span');
  a.innerText = dat.data;
  a.innerHTML = '<b>'+a.innerHTML+'</b>';
  p.appendChild(a)
  p.innerHTML += " has <i>"+dat.what+"</i> the chat!"
  document.getElementById('chat').innerHTML += "<br>"
  p.innerHTML += '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(Date()).substring(16, 24)+'">'+String(Date()).substring(16, 21)+'</span></small></small>'
  if (!stopAnim) {
    p.style.opacity = "0";
    p.style.transition = "0.3s";
    }
  document.getElementById('chat').appendChild(p);
  if (!stopAnim) {
    setTimeout(() => {
    p.style.opacity = "1";
    }, Math.random());
  }
  } else if (dat.type === "delete") {
  let d = document.getElementById(dat.data);
  console.log('yooo')
  if (d) {
  if (d.id === editID) {
  editID = "";
  editmode = false;
  document.getElementById('send').innerText = 'Send';
  }
  d.style.opacity = 0;
  if (d.getElementsByTagName('video')[0]) {
    URL.revokeObjectURL(d.getElementsByTagName('video')[0].src);
    d.getElementsByTagName('video')[0].pause();
  setTimeout(() => {
    d.getElementsByTagName('video')[0].src = null
    d.getElementsByTagName('video')[0].parentNode.removeChild(d.getElementsByTagName('video')[0])
  d.parentNode.removeChild(d);
  }, 300);
} else if (d.getElementsByTagName('img')[0]) {
  URL.revokeObjectURL(d.getElementsByTagName('img')[0].src);
setTimeout(() => {
  d.getElementsByTagName('img')[0].src = null
  d.getElementsByTagName('img')[0].parentNode.removeChild(d.getElementsByTagName('img')[0])
d.parentNode.removeChild(d);
}, 300);
} else if (d.getElementsByTagName('audio')[0]) {
  URL.revokeObjectURL(d.getElementsByTagName('audio')[0].src);
  d.getElementsByTagName('audio')[0].pause();
setTimeout(() => {
  d.getElementsByTagName('audio')[0].src = null
  d.getElementsByTagName('audio')[0].parentNode.removeChild(d.getElementsByTagName('audio')[0])
d.parentNode.removeChild(d);
}, 300);
} else {
  setTimeout(() => {
  d.parentNode.removeChild(d);
  }, 300);
}
  }
  } else if (dat.type === "edit") {
    console.log(dat)
  let d = document.getElementById(dat.id);
  f = d;
  d.getElementsByTagName('span')[1].innerText = ': '+dat.data;
  if (!d.getElementsByTagName('span')[3].innerText.includes('(edited)')) {
  d.getElementsByTagName('span')[3].innerText += ' (edited)'
  }
  } else if (dat.type === "message") {
  let p = document.createElement('span');
  let a = document.createElement('span');
  let b = document.createElement('span');
  let timing = new Date()
  a.innerText = dat.name;
  a.innerHTML = '<b>'+a.innerHTML+'</b>'
  b.innerText = ': '+dat.data;${
    b === 11 || b === 0
      ? `
      if (b.innerText.toLowerCase().includes('merry christmas')) {
      onesnow();
      }
      if (b.innerText.toLowerCase().includes('happy new year')) {
      confetti()
      }`
      : ""
  }p.appendChild(a);
  p.appendChild(b);
  b.innerHTML = b.innerHTML.replaceAll('@Chat Room Broadcast', '<font color="green">@Chat Room Broadcast</font>');
  b.innerHTML = b.innerHTML.replaceAll('@Moderation Bot', '<font color="orange">@Moderation Bot</font>');
  if (document.getElementById('chat').innerHTML !== "") {
  p.innerHTML = "<br>"+p.innerHTML;
  }
  let time = document.createElement('span');
  time.innerHTML = '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(timing).substring(16, 24)+'">'+String(timing).substring(16, 21)+'</span></small></small>'
  p.appendChild(time);
  l = time;
  if (!stopAnim) {
  p.style.opacity = "0";
  p.style.transition = "0.3s";
  }
  if (dat.author === true) {
  let del = document.createElement('button');
  del.innerText = 'Delete';
  let edit = document.createElement('button');
  edit.innerText = 'Edit'
  del.onclick = () => {
  ws.send(JSON.stringify({ type: 'delete', data: dat.id }))
  }
  p.innerHTML += \`&nbsp;&nbsp;\`
  edit.onclick = () => {
  editmode = true;
  document.getElementById('send').disabled = false;
  editID = dat.id;
  editOrigin = p.getElementsByTagName('span')[1].innerText.substring(2);
  document.getElementById('message').value = p.getElementsByTagName('span')[1].innerText.substring(2);
  document.getElementById('send').innerText = 'Cancel';
  }
  let controls = document.createElement('span');
  controls.style.opacity = 0;
  controls.style.transition = "0.3s";
  controls.appendChild(del);
  controls.appendChild(edit);
  p.appendChild(controls);
  setTimeout(() => {
  p.onmouseenter = () => {
    controls.style.opacity = 1;
    //p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 21), String(timing).substring(16, 24));
    }
    p.onmouseleave = () => {
    controls.style.opacity = 0;
    //p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 24), String(timing).substring(16, 21));
    }
  }, 1);
  } else {
}
p.getElementsByTagName('span')[3].onclick = () => {
  if (p.getElementsByTagName('span')[3].innerText.split(' ')[0] === String(timing).substring(16, 21)) {
  p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 21), String(timing).substring(16, 24));
  } else {
    p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 24), String(timing).substring(16, 21));
  }
}
  p.id = dat.id;
  if (dat.emb) {
  console.log('yeas')
  embed = p;
  } else {
  document.getElementById('chat').appendChild(p);
  }
  if (!stopAnim) {
  setTimeout(() => {
  stopAnim = true;
  p.style.opacity = "1";
  stopAnim = false;
  }, Math.random());
}
document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  //window.scrollTo(0, window.innerHeight*2)
  } else if (dat.type === "html") {
  /*document.getElementById('chat').innerHTML += "<br>";
  document.getElementById('chat').innerHTML += dat.data;*/
  let html = document.createElement('span');
  let br = document.createElement('br');
  html.innerHTML = dat.data;
  document.getElementById('chat').appendChild(br);
  document.getElementById('chat').appendChild(html);
  document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  } else if (dat.type === 'addtyping') {
  document.getElementById('a').hidden = false;
  let p = document.createElement('span');
  p.id = dat.data;
  p.innerText = dat.name + ' is typing...'
  typings += 1;
  if (typings > 1) {
  p.innerHTML = "<br>"+p.innerHTML;
  }
  p.style.opacity = "0";
  p.style.transition = "0.3s";
  document.getElementById('typing').appendChild(p);
  setTimeout(() => {
  p.style.opacity = "1";
  }, Math.random());
  } else if (dat.type === 'remtyping') {
  typings -= 1;
  //document.getElementById(dat.data).style.opacity = "0";
  //setTimeout(() => {
  document.getElementById('typing').removeChild(document.getElementById(dat.data))
  if (document.getElementById('typing').innerHTML === "") {
  document.getElementById('a').hidden = true;
  }
//}, 200);
  } else if (dat.type === 'broadcast') {
    console.log('OOOOO')
  let p = document.createElement('span');
  let a = document.createElement('span');
  let b = document.createElement('span');
  a.innerHTML = '<b>Chat Room Broadcast</b>';
  a.style.color = "green";
  b.innerText = ': '+dat.data;
  p.appendChild(a); p.appendChild(b);

  //b.innerHTML = b.innerHTML.replaceAll('**', '[boldend]');
  //b.innerHTML = b.innerHTML.replaceAll('*', '[boldstart]');
  b.innerHTML = b.innerHTML.replace('[b]', '<b>');
  b.innerHTML = b.innerHTML.replace('[/b]', '</b>');
  let timing = new Date()
  p.innerHTML = "<br>"+p.innerHTML;
  let time = document.createElement('span');
  time.innerHTML = '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(timing).substring(16, 24)+'">'+String(timing).substring(16, 21)+'</span></small></small>'
  p.appendChild(time);
  //p.innerHTML += '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(Date()).substring(16, 24)+'">'+String(Date()).substring(16, 21)+'</span></small></small>'
  if (!stopAnim) {
    p.style.opacity = "0";
    p.style.transition = "0.3s";
    }
    p.getElementsByTagName('span')[3].onclick = () => {
      if (p.getElementsByTagName('span')[3].innerText.split(' ')[0] === String(timing).substring(16, 21)) {
      p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 21), String(timing).substring(16, 24));
      } else {
        p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 24), String(timing).substring(16, 21));
      }
    }
  document.getElementById('chat').appendChild(p);
  document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  if (!stopAnim) {
    setTimeout(() => {
    p.style.opacity = "1";
    }, Math.random());
  }
  } else ${
    b === 11 || b === 0
      ? `
  if (dat.type === 'santa') {
    console.log('OOOOO')
  let p = document.createElement('span');
  let a = document.createElement('span');
  let b = document.createElement('span');
  a.innerHTML = '<b>Santa Claus</b>';
  a.className = 'santa'
  b.innerText = ': '+dat.data;
  p.appendChild(a); p.appendChild(b);

  //b.innerHTML = b.innerHTML.replaceAll('**', '[boldend]');
  //b.innerHTML = b.innerHTML.replaceAll('*', '[boldstart]');
  b.innerHTML = b.innerHTML.replace('[b]', '<b>');
  b.innerHTML = b.innerHTML.replace('[/b]', '</b>');
  let timing = new Date()
  p.innerHTML = "<br>"+p.innerHTML;
  let time = document.createElement('span');
  time.innerHTML = '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(timing).substring(16, 24)+'">'+String(timing).substring(16, 21)+'</span></small></small>'
  p.appendChild(time);
  //p.innerHTML += '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(Date()).substring(16, 24)+'">'+String(Date()).substring(16, 21)+'</span></small></small>'
  if (!stopAnim) {
    p.style.opacity = "0";
    p.style.transition = "0.3s";
    }
    p.getElementsByTagName('span')[3].onclick = () => {
      if (p.getElementsByTagName('span')[3].innerText.split(' ')[0] === String(timing).substring(16, 21)) {
      p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 21), String(timing).substring(16, 24));
      } else {
        p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 24), String(timing).substring(16, 21));
      }
    }
  document.getElementById('chat').appendChild(p);
  if (!stopAnim) {
    setTimeout(() => {
    p.style.opacity = "1";
    }, Math.random());
  }
  document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  } else if (dat.type === 'grinch') {
    console.log('OOOOO')
  let p = document.createElement('span');
  let a = document.createElement('span');
  let b = document.createElement('span');
  a.innerHTML = '<b>The Grinch</b>';
  a.className = 'grinch';
  b.innerText = ': '+dat.data;
  p.appendChild(a); p.appendChild(b);

  //b.innerHTML = b.innerHTML.replaceAll('**', '[boldend]');
  //b.innerHTML = b.innerHTML.replaceAll('*', '[boldstart]');
  b.innerHTML = b.innerHTML.replace('[b]', '<b>');
  b.innerHTML = b.innerHTML.replace('[/b]', '</b>');
  let timing = new Date()
  p.innerHTML = "<br>"+p.innerHTML;
  let time = document.createElement('span');
  time.innerHTML = '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(timing).substring(16, 24)+'">'+String(timing).substring(16, 21)+'</span></small></small>'
  p.appendChild(time);
  //p.innerHTML += '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(Date()).substring(16, 24)+'">'+String(Date()).substring(16, 21)+'</span></small></small>'
  if (!stopAnim) {
    p.style.opacity = "0";
    p.style.transition = "0.3s";
    }
    p.getElementsByTagName('span')[3].onclick = () => {
      if (p.getElementsByTagName('span')[3].innerText.split(' ')[0] === String(timing).substring(16, 21)) {
      p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 21), String(timing).substring(16, 24));
      } else {
        p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 24), String(timing).substring(16, 21));
      }
    }
  document.getElementById('chat').appendChild(p);
  if (!stopAnim) {
    setTimeout(() => {
    p.style.opacity = "1";
    }, Math.random());
  }
  document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  } else`
      : ""
  } if (dat.type === 'modbroadcast') {
    console.log('OOOOO')
    let p = document.createElement('span');
    let a = document.createElement('span');
    let b = document.createElement('span');
    a.innerHTML = '<b>Moderation Bot</b>';
    a.style.color = "orange";
    b.innerText = ': '+dat.data;
    p.appendChild(a); p.appendChild(b);
  
    //b.innerHTML = b.innerHTML.replaceAll('**', '[boldend]');
    //b.innerHTML = b.innerHTML.replaceAll('*', '[boldstart]');
    b.innerHTML = b.innerHTML.replace('[b]', '<b>');
    b.innerHTML = b.innerHTML.replace('[/b]', '</b>');
    
    p.innerHTML = "<br>"+p.innerHTML;
    let timing = new Date()
    let time = document.createElement('span');
  time.innerHTML = '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(timing).substring(16, 24)+'">'+String(timing).substring(16, 21)+'</span></small></small>'
  p.appendChild(time);
    //p.innerHTML += '&nbsp;&nbsp;<small><small><span style="user-select: none; cursor: pointer;" title="Today, at '+String(Date()).substring(16, 24)+'">'+String(Date()).substring(16, 21)+'</span></small></small>'
    if (!stopAnim) {
      p.style.opacity = "0";
      p.style.transition = "0.3s";
      }
      p.getElementsByTagName('span')[3].onclick = () => {
        if (p.getElementsByTagName('span')[3].innerText.split(' ')[0] === String(timing).substring(16, 21)) {
        p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 21), String(timing).substring(16, 24));
        } else {
          p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText = p.getElementsByTagName('span')[3].innerText.replaceAll(String(timing).substring(16, 24), String(timing).substring(16, 21));
        }
      } 
    document.getElementById('chat').appendChild(p);
    if (!stopAnim) {
      setTimeout(() => {
      p.style.opacity = "1";
      }, Math.random());
    }
    document.getElementById('chat').scrollTo(0, document.getElementById('chat').innerHeight*2)
document.getElementById('chat').scrollTo(document.getElementById('chat').scrollX, document.getElementById('chat').scrollHeight);
  } else if (dat.type === 'Chooseanothername') {
    namesubmitted = false;
    ${b === 11 || b === 0 ? "snow(true)" : ""}
    document.getElementById('name').disabled = false;
    document.getElementById('message').disabled = true;
    document.getElementById('send').disabled = true;
    document.getElementById('okay').innerText = dat.data;
    document.getElementById('okay').style.color = "red";
    document.getElementById('join').disabled = true;
    setTimeout(() => {
    document.getElementById('okay').innerText = 'Please enter a name.'
    document.getElementById('okay').style.color = "";
    if (document.getElementById('message').value.replaceAll(' ', '').length > 0) {
    document.getElementById('join').disabled = false;
    }
    }, 3000);
    document.getElementById('rest').style.opacity = 0;
      setTimeout(() => {
        document.getElementById('rest').hidden = true;
      document.getElementById('intro').hidden = false;
      setTimeout(() => {
      document.getElementById('intro').style.opacity = 1;
      }, 10);
      }, 500);
  } else if (dat.type === 'stopAnim') {
    stopAnim = true;
  } else if (dat.type === 'resAnim') {
    stopAnim = false;
  } else if (dat.type === "mute") {
    document.getElementById('message').disabled = true;
    document.getElementById('name').disabled = true;
    document.getElementById('send').disabled = true;
    document.getElementById('okay').innerText = 'You have been muted. Please wait.'
    document.getElementById('limit').innerText = '(?/25)'
    muted = true;
    console.log('lol')
} else if (dat.type === "unmute") {
  console.log('ah')
  if (document.getElementById('name').value.replaceAll(' ', '').length > 0) {
    console.log('aha')
  document.getElementById('message').disabled = false;
  document.getElementById('send').disabled = false;
  } else if (dat.type === "lol") {
  let m = new File([dat.data], "theia.png", {
lastModified: Date.now(),
type: 'image/png'
})
console.log(URL.createObjectURL(m))
  } else {
    console.log('ahe')
  document.getElementById('name').disabled = false;
  document.getElementById('okay').innerText = 'Please enter a name.'
  document.getElementById('limit').innerText = '('+document.getElementById('name').value.length+'/25)'
  }
  muted = false;
}
  }
  ws.onclose = () => {
  console.log('closed')
  reconn = true;
  setTimeout(() => {
  recon()
  }, 2000+Number(Math.random()*2));
  if (namesubmitted === false) {
  document.getElementById('name').disabled = true;
  document.getElementById('join').disabled = true;
  document.getElementById('okay').innerText = 'Reconnecting...'
  }
  typings = 0;
  document.getElementById('typing').innerHTML = ""
  document.getElementById('a').hidden = true;
  typinglol = false;
  }
}
recon()
let typinglol = false;
let reader = new FileReader();
document.getElementById('e').oninput = () => {
  ws.send(JSON.stringify({ type: "thing", data: document.getElementById('e').files[0].type }))
  reader.readAsArrayBuffer(document.getElementById('e').files[0]);
}
  document.getElementById('send').onclick = () => {
  if (offline === true) {
  document.getElementById('o').hidden = false;
  }
  if (editmode === true) {
    if (document.getElementById('message').value === editOrigin || document.getElementById('message').value.replaceAll(' ').length === 0) {
    editmode = false;
    document.getElementById('send').innerText = 'Send';
    editID = "";
    document.getElementById('message').value = "";
    } else {
    editmode = false;
    ws.send(JSON.stringify({ type: 'edit', data: document.getElementById('message').value, id: editID }));
    document.getElementById('send').innerText = 'Send';
    document.getElementById('message').value = "";
    editID = "";
    }
  } else if (document.getElementById('message').value.replaceAll(' ', '').length > 0) {
    if (typinglol === true) {typinglol = false; ws.send(JSON.stringify({type: 'stoptyping'}))}
  if (document.getElementById('message').value.startsWith('/')) {
  console.log('oo')
  ws.send(JSON.stringify({type: 'cmd', data: document.getElementById('message').value}))
  if (!document.getElementById('message').value.startsWith('/eval')) {
  document.getElementById('message').value = ""
  document.getElementById('send').disabled = true;
  }
  } else {
    console.log('aw')
    if (document.getElementById('e').files[0]) {
      //reader.onload = () => {
        console.log('whoop')
      console.log('whip')
      ws.send(JSON.stringify({ type: 'thing', data: document.getElementById('e').files[0].type }))
      let no = new FileReader()
      no.readAsArrayBuffer(document.getElementById('e').files[0]);
      ws.send(JSON.stringify({type: 'message', data: document.getElementById('message').value, emb: true}))
      no.onload = () => {
  ws.send(no.result);
  document.getElementById('message').value = ""
  document.getElementById('e').value = ""
  document.getElementById('send').disabled = true;
      };
      //}
    } else {
      ws.send(JSON.stringify({type: 'message', data: document.getElementById('message').value}))
      console.log('whip')
  document.getElementById('message').value = ""
  document.getElementById('send').disabled = true;
    }
}
  } else {
  if (editmode === false) {
  document.getElementById('send').disabled = true;
  }
  }
  }
  document.getElementById('message').oninput = () => {
  if (editmode === true) {
  if (document.getElementById('message').value === editOrigin || document.getElementById('message').value.replaceAll(' ').length === 0) {
  document.getElementById('send').innerText = 'Cancel';
  } else {
  document.getElementById('send').innerText = "Edit";
  }
  } else {
  if (document.getElementById('message').value.startsWith('/')) {
    document.getElementById('message').maxLength = 10000;
  } else {
    document.getElementById('message').maxLength = 75;
    if (document.getElementById('message').value.length > 75) {
    document.getElementById('message').value = document.getElementById('message').value.substring(0, 75)
    }
  }
  if (document.getElementById('message').value.replaceAll(' ', '').length > 0) {
  document.getElementById('send').disabled = false;
  } else {
  document.getElementById('send').disabled = true;
  }
  if (document.getElementById('message').value.replaceAll(' ', '').length > 0 && typinglol === false && editmode === false) {
  typinglol = true;
  ws.send(JSON.stringify({type: 'starttyping'}))
  } else if (typinglol === true && document.getElementById('message').value.replaceAll(' ', '').length === 0) {
  typinglol = false;
  ws.send(JSON.stringify({type: 'stoptyping'}))
  }
}
  }
  document.getElementById('name').oninput = () => {
  if (document.getElementById('name').value.replaceAll(' ', '').length === 0 || document.getElementById('name').value.length > 25) {
    document.getElementById('join').disabled = true;
    document.getElementById('limit').innerText = '('+document.getElementById('name').value.length+'/25)';
  } else {
  document.getElementById('join').disabled = false;
  document.getElementById('limit').innerText = '('+document.getElementById('name').value.length+'/25)'
  }
  }
  
  document.getElementById('spectate').onclick = () => {
    spectate = true;
    namesubmitted = true;
    ${b === 11 || b === 0 ? "snow(false)" : ""}
    document.getElementById('join').disabled = true;
    document.getElementById('chatinput').hidden = true;
    document.getElementById('back').hidden = false;
    document.getElementById('intro').style.opacity = 0;
    setTimeout(() => {
      document.getElementById('intro').hidden = true;
    document.getElementById('rest').hidden = false;
    setTimeout(() => {
    document.getElementById('rest').style.opacity = 1;
    let span = document.createElement('span');
    span.innerHTML = '&nbsp;&nbsp;Press ESC to return to homescreen&nbsp;&nbsp;';
    span.style = "background-color: grey; opacity: 0; transition: 0.5s; border-radius: 3px; color: white; font-family: sans-serif; transform: translate(-50%, -50%); top: 90%; left: 50%; position: fixed; z-index: 500;"
    document.body.appendChild(span);
    setTimeout(() => {
    span.style.opacity = 1;
    }, 50);
    setTimeout(() => {
    span.style.opacity = 0;
    setTimeout(() => {
    span.parentNode.removeChild(span);
    }, 500);
    }, 4500);
    }, 10);
    }, 500);
  }
  document.getElementById('join').onclick = () => {
    if (document.getElementById('name').value.length > 25) {
      document.getElementById('okay').innerText = 'Your name is over 25 characters!'
      document.getElementById('okay').style.color = "red";
      setTimeout(() => {
      document.getElementById('okay').innerText = 'Please enter a name.'
      document.getElementById('okay').style.color = "";
      }, 2000);
      document.getElementById('join').disabled = true;
    } else if (document.getElementById('name').value.replaceAll(' ', '').length > 0) {
      ${b === 11 || b === 0 ? "snow(false)" : ""}
      namesubmitted = true;
      document.getElementById('name').disabled = true;
      document.getElementById('message').disabled = false;
      document.getElementById('send').disabled = false;
      ws.send(JSON.stringify({type: 'name', data: document.getElementById('name').value}));
      document.getElementById('intro').style.opacity = 0;
      setTimeout(() => {
        document.getElementById('intro').hidden = true;
      document.getElementById('rest').hidden = false;
      setTimeout(() => {
      document.getElementById('rest').style.opacity = 1;
      }, 10);
      }, 500);
      } else {
      if (document.getElementById('name').value.replaceAll(' ', '').length === 0) {
      document.getElementById('okay').innerText = "You did not enter a name yet!"
    document.getElementById('okay').style.color = "red";
    setTimeout(() => {
    document.getElementById('okay').innerText = 'Please enter a name.'
    document.getElementById('okay').style.color = "";
    }, 2000);
  }
    document.getElementById('join').disabled = true;
      }
  }
  </script>`);
    view += 1;
    fs.writeFile("./views.js", "exports.views = " + view, (err) => {});
  }
});

// --- WebSocket Server ---
const wss = new WebSocket.Server({ server });
let websockets = [];
let clientCount = 0;
let messages = [];
let mutedIPS = [];
let names = [];
let settings = {
  CHAT_HISTORY_SAVE: false,
};
let OIQWUEIQUWEMXOIQJWS = require("./sett.js");
settings = JSON.parse(JSON.stringify(OIQWUEIQUWEMXOIQJWS.settings));
messages = JSON.parse(JSON.stringify(mess.messages));
if (messages.length > 30) {
  messages = [];
  messages.push(
    JSON.stringify({
      type: "html",
      data: '<font color="red"><b>Messages before these were deleted due to storage limitations.</b></font>',
    })
  );
  fs.writeFile("./messages.js", `exports.messages = []`, (err) => {});
}
let typings = "";
function broadcast(message, exclude) {
  if (exclude) {
    for (let ws of websockets) {
      if (ws.id !== exclude) {
        ws.send(message);
      }
    }
  } else {
    for (let ws of websockets) {
      ws.send(message);
    }
  }
}
wss.on("connection", (ws, req) => {
  console.log(req.headers["x-original-forwarded-for"].split(",")[0]);
  const fetch = require("node-fetch");
  let threats = [];
  let IPs = [];
  if (
    !IPs.includes(req.headers["x-original-forwarded-for"].split(",")[0]) &&
    !threats.includes(req.headers["x-original-forwarded-for"].split(",")[0])
  ) {
    fetch(
      `https://api.ipdata.co/${
        req.headers["x-original-forwarded-for"].split(",")[0]
      }?api-key=fb4e79724a5ae24387736e41788054acb0338be745675279b03ce10a`
    )
      .then((res) => res.json())
      .then((data) => {
        console.log("noice");
        if (
          data.threat.is_tor === true ||
          data.threat.is_icloud_relay === true ||
          data.threat.is_proxy === true ||
          data.threat.is_datacenter === true ||
          data.threat.is_anonymous === true ||
          data.threat.is_known_attacker === true ||
          data.threat.is_known_abuser === true ||
          data.threat.is_threat === true ||
          data.threat.is_bogon === true ||
          data.threat.is_tor === "true" ||
          data.threat.is_icloud_relay === "true" ||
          data.threat.is_proxy === "true" ||
          data.threat.is_datacenter === "true" ||
          data.threat.is_anonymous === "true" ||
          data.threat.is_known_attacker === "true" ||
          data.threat.is_known_abuser === "true" ||
          data.threat.is_threat === "true" ||
          data.threat.is_bogon === "true"
        ) {
          console.log("e");
          ws.pause();
          threats.push(req.headers["x-original-forwarded-for"]);
        } else {
          console.log("o");
          IPs.push(req.headers["x-original-forwarded-for"]);
        }
      });
  }
  if (threats.includes(req.headers["x-original-forwarded-for"].split(",")[0])) {
    console.log("ea");
    ws.pause();
    threats.push(req.headers["x-original-forwarded-for"]);
  }
  if (IPs.includes(req.headers["x-original-forwarded-for"].split(",")[0])) {
    console.log("oa");
  }
  /*for (let i = 0; i < messages.length; i++) {
    if (messages.length > 0) {
      ws.send(JSON.stringify({ type: "stopAnim" }));
      ws.send(messages[i]);
      ws.send(JSON.stringify({ type: "resAnim" }));
    }
  }*/
  console.log("Client connected");
  if (!websockets.includes(ws)) {
    websockets.push(ws);
  }
  if (mutedIPS.includes(req.headers["x-original-forwarded-for"])) {
    ws.send(JSON.stringify({ type: "mute" }));
    ws.pause();
    ws.muted = true;
    ws.send(
      JSON.stringify({
        type: "modbroadcast",
        data: "You are currently muted. Please wait to be unmuted.",
      })
    );
    let m = setInterval(() => {
      if (ws.closed === true) {
        clearInterval(m);
      }
      if (!mutedIPS.includes(req.headers["x-original-forwarded-for"])) {
        clearInterval(m);
        ws.send(JSON.stringify({ type: "unmute" }));
        ws.muted = false;
        ws.resume();
      }
    }, 0);
  }
  ws.on("message", (msg) => {
    try {
      let dat = JSON.parse(msg.toString());
      console.log(dat);
      if (dat.type === "name" && !ws.name) {
        if (
          dat.data.toLowerCase().includes("nigg") ||
          dat.data.toLowerCase().includes("slut") ||
          dat.data.toLowerCase().includes("pussy") ||
          dat.data.toLowerCase().includes("sex") ||
          dat.data.toLowerCase().includes("penis") ||
          dat.data.toLowerCase().includes("testicles") ||
          dat.data.toLowerCase().includes("chat room broadcast") ||
          dat.data.toLowerCase().includes("moderation bot") ||
          dat.data.toLowerCase().includes("broadcast") ||
          dat.data.toLowerCase().includes("moderation") ||
          dat.data.toLowerCase().includes("moderator") ||
          dat.data.toLowerCase().includes("ban") ||
          dat.data.toLowerCase().includes("\x7f") ||
          dat.data.toLowerCase().includes("ㅤ") ||
          dat.data.toLowerCase().includes("‎")
        ) {
          /*ws.send(
            JSON.stringify({
              type: "html",
              data: `<font color="red"><b>Sorry! Please choose another name.</b></font>`,
            })
          );*/
          ws.send(
            JSON.stringify({
              type: "Chooseanothername",
              data: "Sorry! Please choose another name.",
            })
          ); //(CH-oose AN-other NA-me)
        } else if (dat.data.replaceAll(" ", "").length > 0) {
          ws.id = Math.random().toString().substring(2);
          let taken = false;
          for (let wsa of websockets) {
            if ((String(wsa.name) === String(dat.data)) === true) {
              taken = true;
            }
          }
          if (taken === true) {
            ws.name = String("User_" + ws.id).substring(0, 25);
            console.log("aa");
            console.log(String(wsa.name) === String(dat.data));
            console.log(wsa.name);
            console.log(dat.data);
          } else {
            ws.name = dat.data.substring(0, 25);
            console.log("what? how?!");
          }
          ws.typing = false;
          clientCount++;
          names.push(ws.name);
          broadcast(
            /*JSON.stringify({
              type: "name",
              data: String(ws.name),
              what: "joined",
            })*/
            JSON.stringify({
              type: "broadcast",
              data: "[b]" + ws.name + "[/b] has joined the chat!",
            })
          );
          ws.lastmessage = Date.now() - 100;
          ws.mute = 20;
          ws.messages = [];
          ws.cooldownho = false;
          ws.muted = false;
          messages.push(
            /*JSON.stringify({
              type: "name",
              data: String(ws.name),
              what: "joined",
            })*/
            JSON.stringify({
              type: "broadcast",
              data: "[b]" + ws.name + "[/b] has joined the chat!",
            })
          );
          if (dat.data.length > 25) {
            ws.send(
              JSON.stringify({
                type: "html",
                data: `<font color="red"><b>Your name cannot be longer than 25 characters!<${"/"}b><${"/"}font>`,
              })
            );
          }
        } else {
          /*ws.send(
            JSON.stringify({
              type: "html",
              data: `<font color="red"><b>Please enter a valid username!<${"/"}b><${"/"}font>`,
            })
          );*/
          ws.send(
            JSON.stringify({
              type: "Chooseanothername",
              data: "Please enter a valid username!",
            })
          );
        }
      } /*else if (dat.type === "ping") {
        ws.send(JSON.stringify({ type: "pong" }));
        (Does not do a thing)
      } */ else if (!ws.name) {
        /*ws.send(
          JSON.stringify({
            type: "html",
            data: `<font color="red"><b>You cannot send a message without a name!<${"/"}b><${"/"}font>`,
          })
        );*/
        ws.send(
          JSON.stringify({
            type: "Chooseanothername",
            data: "You can't send a message without a name!",
          })
        );
      } else if (dat.type === "thing") {
        broadcast(JSON.stringify({ type: "thing", data: dat.data }));
      } else if (dat.type === "starttyping" && ws.muted === false) {
        if (ws.typing === false) {
          ws.typing = true;
          broadcast(
            JSON.stringify({ type: "addtyping", data: ws.id, name: ws.name })
          );
        }
      } else if (dat.type === "stoptyping") {
        if (ws.typing === true) {
          ws.typing = false;
          broadcast(
            JSON.stringify({ type: "remtyping", data: ws.id, name: ws.name })
          );
        }
      } else if (dat.type === "cmd") {
        let command = String(dat.data).substring(1);
        if (command.startsWith("broadcast")) {
          broadcast(
            JSON.stringify({
              type: "broadcast",
              data: command.substring(10),
            })
          );
        } else if (command.startsWith("eval")) {
          ws.send(
            JSON.stringify({
              type: "html",
              data: "<u><b>EVAL OUTPUT</b></u> - " + eval(command.substring(5)),
            })
          );
        } else if (command.startsWith("id")) {
          for (let wsa of websockets) {
            if (wsa.name === command.substring(3)) {
              ws.send(
                JSON.stringify({
                  type: "html",
                  data:
                    `ID = <span style="user-select: all">` +
                    wsa.id +
                    `</span>.`,
                })
              );
            }
          }
          if (command.substring(3) === "Moderation Bot") {
            ws.send(
              JSON.stringify({
                type: "html",
                data: `ID = <span style="user-select: all">1110289370885137</span>.`,
              })
            );
          } else if (command.substring(3) === "Chat Room Broadcast") {
            ws.send(
              JSON.stringify({
                type: "html",
                data: `ID = <span style="user-select: all">1238712932811282</span>.`,
              })
            );
          }
        } else if (command.startsWith("mute")) {
          let who = command.substring(5).split("&r=")[0];
          let reason = command
            .substring(5)
            .split("&r=")[1]
            .replaceAll(command.substring(5).split("&d=")[1], "")
            .replaceAll("&d=", "");
          let duration = command.substring(5).split("&d=")[1];
          for (let ws of websockets) {
            if (ws.id === String(who)) {
              console.log("aaa");
              ws.muted = true;
              broadcast(
                JSON.stringify({
                  type: "modbroadcast",
                  data:
                    "[b]" +
                    ws.name +
                    "[/b] has been muted for " +
                    duration +
                    ` seconds. Reason: ${reason ? reason : "Unspecified."}`,
                })
              );
              ws.muted = true;
              ws.send(
                JSON.stringify({
                  type: "mute",
                })
              );
              mutedIPS.push(req.headers["x-original-forwarded-for"]);
              setTimeout(() => {
                ws.muted = false;
                mutedIPS.splice(req.headers["x-original-forwarded-for"]);
                ws.send(
                  JSON.stringify({
                    type: "unmute",
                  })
                );
              }, Number(String(duration + "000")));
            }
          }
        } else {
          let id = String(Math.random()).substring(2);
          broadcast(
            JSON.stringify({
              type: "message",
              name: String(ws.name),
              data: String(dat.data).replaceAll("\n", "").substring(0, 75),
              id: id,
              author: false,
            }),
            ws.id
          );
          ws.send(
            JSON.stringify({
              type: "message",
              name: String(ws.name),
              data: String(dat.data).replaceAll("\n", "").substring(0, 75),
              id: id,
              author: true,
            })
          );
          ws.send(
            JSON.stringify({
              type: "html",
              data: `<font color="red"><b>Command doesn't exist.<${"/"}b><${"/"}font>`,
            })
          );
        }
      } else if (dat.type === "delete") {
        broadcast(
          JSON.stringify({
            type: "delete",
            data: dat.data,
          })
        );
      } else if (dat.type === "edit") {
        if (ws.messages.includes(dat.id)) {
          broadcast(
            JSON.stringify({
              type: "edit",
              data: dat.data.substring(0, 75),
              id: dat.id,
            })
          );
        } else {
          ws.send(
            JSON.stringify({
              type: "html",
              data: "You cannot edit a message you did not send!",
            })
          );
        }
      } else if (dat.type === "message") {
        if (
          String(dat.data).replaceAll(" ", "").length > 0 &&
          ws.muted === false
        ) {
          if (Number(Date.now() - ws.lastmessage) < 200) {
            broadcast(
              JSON.stringify({
                type: "modbroadcast",
                data:
                  "[b]" +
                  ws.name +
                  "[/b] has been muted for " +
                  ws.mute +
                  " seconds. Reason: Potential spam.",
              })
            );
            ws.muted = true;
            ws.send(
              JSON.stringify({
                type: "mute",
              })
            );
            mutedIPS.push(req.headers["x-original-forwarded-for"]);
            setTimeout(() => {
              ws.muted = false;
              mutedIPS.splice(req.headers["x-original-forwarded-for"]);
              ws.send(
                JSON.stringify({
                  type: "unmute",
                })
              );
            }, Number(String(ws.mute + "000")));
            ws.mute += 10;
          } else if (String(dat.data).toLowerCase().includes("nigg")) {
            broadcast(
              JSON.stringify({
                type: "modbroadcast",
                data:
                  "[b]" +
                  ws.name +
                  "[/b] has been muted for " +
                  ws.mute +
                  " seconds. Reason: No, no, no :)",
              })
            );
            ws.muted = true;
            ws.send(
              JSON.stringify({
                type: "mute",
              })
            );
            mutedIPS.push(req.headers["x-original-forwarded-for"]);
            setTimeout(() => {
              ws.muted = false;
              mutedIPS.splice(req.headers["x-original-forwarded-for"]);
              ws.send(
                JSON.stringify({
                  type: "unmute",
                })
              );
            }, Number(String(ws.mute + "000")));
            ws.mute += 20;
          } else {
            let id = String(Math.random()).substring(2);
            /*db.send(
              `**${ws.name}**: ${dat.data
                .replaceAll("\n", "")
                .substring(0, 75)}`
            );*/
            ws.messages.push(id);
            if (dat.emb) {
              broadcast(
                JSON.stringify({
                  type: "message",
                  name: String(ws.name),
                  data: String(dat.data).replaceAll("\n", "").substring(0, 75),
                  id: id,
                  emb: dat.emb,
                  author: false,
                }),
                ws.id
              );
              ws.send(
                JSON.stringify({
                  type: "message",
                  name: String(ws.name),
                  data: String(dat.data).replaceAll("\n", "").substring(0, 75),
                  id: id,
                  emb: dat.emb,
                  author: true,
                })
              );
            } else {
              broadcast(
                JSON.stringify({
                  type: "message",
                  name: String(ws.name),
                  data: String(dat.data).replaceAll("\n", "").substring(0, 75),
                  id: id,
                  author: false,
                }),
                ws.id
              );
              ws.send(
                JSON.stringify({
                  type: "message",
                  name: String(ws.name),
                  data: String(dat.data).replaceAll("\n", "").substring(0, 75),
                  id: id,
                  author: true,
                })
              );
            }
            if (
              dat.data.toLowerCase().includes("ho ho ho") &&
              ws.cooldownho === false
            ) {
              ws.cooldownho = true;
              setTimeout(() => {
                ws.cooldownho = false;
              }, 10000);
              let messa = [
                "Ho Ho Ho!",
                "Ho HO ho!",
                "ho ho ho!",
                "HO HO HO!",
                "Ho ho ho! :)",
                "ho ho ho! :D",
              ];
              let messag = [
                "eh eh eh!",
                "He HE he!",
                "eh eh eh!",
                "OH OH EH!",
                "Oh eh oh! >:)",
                "oh oh oh! >:D",
                "ooooooh :<",
              ];
              messag = messag[Math.floor(Math.random() * messag.length)];
              let mess = "";
              setTimeout(() => {
                broadcast(
                  JSON.stringify({
                    type: "santa",
                    data: "Ho Ho Ho!",
                  })
                );
                mess = messa[Math.floor(Math.random() * messa.length)];
              }, 1000);
              setTimeout(() => {
                broadcast(
                  JSON.stringify({
                    type: "broadcast",
                    data: mess,
                  })
                );
                mess = messa[Math.floor(Math.random() * messa.length)];
              }, 2000);
              setTimeout(() => {
                broadcast(
                  JSON.stringify({
                    type: "modbroadcast",
                    data: mess,
                  })
                );
                mess = messa[Math.floor(Math.random() * messa.length)];
              }, 3000);
              setTimeout(() => {
                broadcast(
                  JSON.stringify({
                    type: "grinch",
                    data: messag,
                  })
                );
              }, 4000);
            }
            ws.lastmessage = Date.now();
            messages.push(
              JSON.stringify({
                type: "message",
                name: String(ws.name),
                data: String(dat.data).replaceAll("\n", "").substring(0, 75),
              })
            );
            if (dat.data.includes("@Chat Room Broadcast")) {
              setTimeout(() => {
                broadcast(
                  JSON.stringify({
                    type: "broadcast",
                    data: "Bruh why you not leave me alone :(",
                  })
                );
              }, 300);
            }
            if (dat.data.includes("@Moderation Bot")) {
              setTimeout(() => {
                broadcast(
                  JSON.stringify({
                    type: "modbroadcast",
                    data: "Bro shut up i ain't helping you/your friend who is muted >:(",
                  })
                );
              }, 400);
            }
          }
          if (dat.data.length > 75) {
            ws.send(
              JSON.stringify({
                type: "html",
                data: `<font color="red"><b>Your message cannot over 75 characters!<${"/"}b><${"/"}font>`,
              })
            );
          }
        }
      }
    } catch (error) {
      broadcast(msg);
      console.log(msg);
      //console.error(error);
      console.log(msg);
      /*ws.send(
        JSON.stringify({
          type: "html",
          data: '<b><font color="red">Something went wrong while parsing the message. Sorry!</font></b>',
        })
      );*/
    }
    fs.writeFile(
      "./messages.js",
      `exports.messages = ${JSON.stringify(messages)}`,
      (err) => {}
    );
  });

  ws.on("close", () => {
    console.log(ws.name + " disconnected");
    if (ws.name) {
      if (clientCount !== 0 && ws.closed === false) {
        ws.closed = true;
        clientCount -= 1;
      }

      names.splice(ws.name);
      broadcast(
        /*JSON.stringify({
          type: "name",
          data: String(ws.name),
          what: "left",
        })*/
        JSON.stringify({
          type: "broadcast",
          data: "[b]" + ws.name + "[/b] has left the chat!",
        })
      );
      messages.push(
        /*JSON.stringify({
          type: "name",
          data: String(ws.name),
          what: "left",
        })*/
        JSON.stringify({
          type: "broadcast",
          data: "[b]" + ws.name + "[/b] has left the chat!",
        })
      );
      if (ws.typing === true) {
        broadcast(
          JSON.stringify({ type: "remtyping", data: ws.id, name: ws.name })
        );
        ws.typing = false;
      }
      ws.name = "Unknown_User_" + ws.id;
    }
  });
});

// Start server
server.listen(8080, () => {
  console.log("HTTP + WS server running on http://localhost:8080");
});
